### ISSUE TITLE
COSMA cublas crash after job finished

### ISSUE THREAD

**Issue by yaoyi92** [eth-cscs/COSMA#100]
I realized I cannot reopen the issue #87 

copy the question here. Sorry for the confusion.

=====

Hi @kabicm ,
I am able to redo the test again and the problem still exists with v2.5.0 and the master branch. Does COSMA use a wrapper over MPI_Finalize()? I notice a similar issue on Summit here with another code that is wrapping over MPI_Finalize LLNL/Caliper#392.

If that's the case, my question becomes: Is it possible to manually finalize COSMA?

A related question here: if I called COSMA, does it take the GPU memory after the gemm calls? Is it possible to control those GPU memories? I guess I am looking for something like initiating and finalizing a COSMA environment over a certain code region and free up the GPU memories when outside the code region.

Best wishes,
Yi

**Comment by kabicm** [comment]
Is the problem you mentioned still present with the latest version: [COSMA-v2.6.1](https://github.com/eth-cscs/COSMA/releases/tag/v2.6.1)?

**Comment by kabicm** [comment]
Btw, the gpu devices should be set outside of COSMA (e.g. in cp2k) and COSMA will just inherit the devices that were previously set. This could cause the issue you are referring to.

**Comment by yaoyi92** [comment]
Sorry for the late reply. Yes, the problem is still there. However, the message seems to show up after the job finished so it doesn't bother too much for now. We used the pxgemm_cosma wrapper you provided and we initialized our own GPU devices in our code (FHI-aims). It feels like the same situation with cp2k. Is there a solution for that?

Do you think it worth to try the destructor? Do you have a fortran wrapper for the destructor?

**Comment by alazzaro** [comment]
> Sorry for the late reply. Yes, the problem is still there. However, the message seems to show up after the job finished so it doesn't bother too much for now. We used the pxgemm_cosma wrapper you provided and we initialized our own GPU devices in our code (FHI-aims). It feels like the same situation with cp2k. Is there a solution for that?

The CP2K problem was really not due to COSMA. The MPI implementation registers some of the GPU buffers used in MPI communications. The error is that you get a double finalization (in MPI and COSMA), but not the problem is fixed and we leave COSMA to finalize.
