### ISSUE TITLE
enable overlap comm with computation for cosma_miniapp

### ISSUE THREAD

**Issue by sagnbasu** [eth-cscs/COSMA#122]
Hi @kabicm 

I see that cosma's strategy implementation disables calling the `comm->overlap_comm_and_comp(...)`  from multiply.cpp for the cosma_miniapp program. I tried various matrix sizes (tall, square, etc) but I am not able to see the overlap path getting executed. 

Is there any particular matrix dimension which can trigger the overlap execution flow from the cosma_miniapp ? I am testing the miniapp in a 4 node cluster with AMD GPU+CPU, and the maximum MPI rank is 16.

Thanks for your time.

**Comment by kabicm** [comment]
Hi @sagnbasu, the overlap of communication and computation can be enabled by setting the environment variable:
```
export COSMA_OVERLAP_COMM_AND_COMP=ON
```
You can see the list of all the tunable parameters here:
https://github.com/eth-cscs/COSMA#tunable-parameters

Hope it helps!

**Comment by kabicm** [comment]
I will close this issue now, but feel free to reopen it if the problem persists!
