### ISSUE TITLE
Single node multi-GPU map problem

### ISSUE THREAD

**Issue by wanghemeng** [eth-cscs/COSMA#146]
I'm testing COSMA with GPU support on a node with 8 GPUs.

But when I execute command like:

`mpirun --allow-run-as-root -np 8 ./miniapp/cosma_miniapp -m 8192 -n 8192 -k 8192 -t float -r 20`

Only one GPU are used and other GPUs are idle. And so the performance of 8 or 4 or 2 GPUs are slower than single GPU.

I build cosma with (Scalack in MKL failed and I didn't try others, so just turn it off):

`cmake -DCOSMA_BLAS=CUDA -DCOSMA_SCALAPACK=OFF -DCMAKE_INSTALL_PREFIX=/root/cosma ..`

Since I'm new to cosma, any clue about this problem will be helpful. 

THANKS!

**Comment by wanghemeng** [comment]
Fixed by adding a device setting function in the front of mini-app

`gpu::runtime_api::set_device(rank);`

Thanks again.

**Comment by simonpintarelli** [comment]
Hello @wanghemeng , sorry for the slow reply.

The usual way is to `export CUDA_VISIBLE_DEVICES` . This can be done using either the scheduler (slurm) or using a wrapper bash script.
