### ISSUE TITLE
Multi GPU support

### ISSUE THREAD

**Issue by kabicm** [eth-cscs/COSMA#23]
At the moment, it is assumed that each rank uses a single GPU. However, we should also be able to deal with mutliple GPUs being available to the same MPI rank.

**Comment by kabicm** [comment]
This issue will be reopened later since it is already possible to run COSMA on multiple GPUs with 1:1 rank per GPU ratio.

**Comment by rohany** [comment]
Based on this issue, does COSMA not yet support multiple GPUs?

**Comment by kabicm** [comment]
COSMA supports multiple GPUs, but at the moment, you should run it with 1:1 ranks to gpus ratio. For example, if your node has 6 GPUs, you should then also run 6 ranks per node, so that each rank is mapped to a single GPU, which is what people usually anyway do.

Would this be sufficient for your use case? You can submit a feature request through a new issue If you have a concrete use-case, where a different ratio is benefitial. We will then surely consider enabling COSMA to run on any configuration.

**Comment by rohany** [comment]
I think that this should work for me. In a setup like this, can COSMA take advantage of the NVLink between the GPUs if it is present?
