### ISSUE TITLE
Compilation fails with CUDA 9

### ISSUE THREAD

**Issue by shoshijak** [eth-cscs/COSMA#24]
When compiling COSMA using CUDA 9, and the following instructions:

```
cmake -DCOSMA_BLAS=CUDA -DCOSMA_SCALAPACK=CUSTOM ..
make -j
```

The compilation fails with: 
```bash
/COSMA/benchmarks/gpu_gemm_cublas.cpp:5:10: fatal error: cublasLt.h: No such file or directory
 #include <cublasLt.h>
          ^~~~~~~~~~~~
compilation terminated.
```

The header `cublasLt.h` is indeed not included in CUDA 9. 
Compiling with CUDA 10, however, works fine.

**Comment by kabicm** [comment]
Thanks @shoshijak for catching this! It should be fixed in commit: #e50042a5a4f412ed906b01d0d8010181efcea222.
