### ISSUE TITLE
Bundled semiprof package has no license

### ISSUE THREAD

**Issue by oschuett** [eth-cscs/COSMA#29]
Please add a license to the bundled [semiprof](https://github.com/kabicm/semiprof) repository or simply rebase onto the [original](https://github.com/bcumming/semiprof) repository.

**Comment by kabicm** [comment]
Thanks @oschuett for catching this! I updated now the bundled semiprof repo, so it also contains the Licence. 

Btw, the PR to the original repo is created and has been waiting for some time now. As soon as our PR gets merged, we can then use the original repo directly.

**Comment by oschuett** [comment]
Thanks for the quick response :-)
