### ISSUE TITLE
Division by zero in interval.cpp

### ISSUE THREAD

**Issue by oschuett** [eth-cscs/COSMA#33]
The CP2K scaling test [found](https://dashboard.cp2k.org/archive/scaling/commit_4c021fa84001910a05e02aba7306f02b5dd5a3ff.txt) an _erroneous arithmetic operation_ at [interval.cpp:41](https://github.com/eth-cscs/COSMA/blob/master/src/cosma/interval.cpp#L41). Presumably, the other divisions in that file are also at risk.

**Comment by kabicm** [comment]
@oschuett Thanks for the issue! Is COSMA here built with MKL? Because I see `OMP_NUM_THREADS` set but `MKL_NUM_THREADS`.

**Comment by oschuett** [comment]
It's build with the [default toolchain](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/Dockerfile). So, Openblas and Scalapack. We never set `MKL_NUM_THREADS` in our tests. The div-by-zero occurred in [H2O-32.inp](https://github.com/cp2k/cp2k/blob/master/benchmarks/QS/H2O-32.inp) with a single MPI rank and 8 OpenMP threads.

**Comment by kabicm** [comment]
Thanks, I am able to reproduce it. It doesn't seem like a serious bug, just the wrong division strategy is being produced. I will work on it.

**Comment by oschuett** [comment]
I think, it's best to avoid divisions by zero as they gives undefined results.
In CP2K we often use `foo / MAX(1,bar)` for these edge cases.

Btw, personally I'm a big fan of floating point exception (which trigger for integers too). They can be very useful while adding virtually no overhead.

**Comment by kabicm** [comment]
Fixed! Not sure if that would just hide these bugs even more?

**Comment by oschuett** [comment]
Thanks! Of course, catching the these edge cases in a single place, as you did, is the best solution :-)

**Comment by kabicm** [comment]
We will publish soon (probably tomorrow) the version `2.1`, which will include one more feature and will have this bug fixed, so that we can also update it in cp2k :)
