### ISSUE TITLE
libgrid2grid library installed in the wrong directory

### ISSUE THREAD

**Issue by pseewald** [eth-cscs/COSMA#60]
I try to build and install COSMA on piz daint:
`source scripts/piz_daint_gpu.sh`
then
```
cmake -DCOSMA_BLAS=CUDA -DCOSMA_SCALAPACK=MKL -DCMAKE_INSTALL_PREFIX=<installation dir>/cosma ..
make -j 8
make install
```

All library files are copied to the location `<installation dir>/cosma/lib64` but `libgrid2grid.a` is copied to `<installation dir>/cosma/lib`.

**Comment by kabicm** [comment]
Thanks Patrick for reporing this issue. @haampie has just fixed it! :)
