### ISSUE TITLE
test.scalar_matmul never ends

### ISSUE THREAD

**Issue by antoscha** [eth-cscs/COSMA#66]
Hi,

test.scalar_matmul is probably broken: it is computed endlessly with any BLAS flavor (OPENBLAS, MKL, or CUDA). CMake options are:
```
  cmake ../cosma \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DBUILD_SHARED_LIBS=ON \
          -DCOSMA_BLAS=CUSTOM \
          -DCOSMA_SCALAPACK=CUSTOM \
          -DMPIEXEC_PREFLAGS='--oversubscribe'
```
Compilers and libraries: GCC 10.2.0, OpenMPI, CUDA 11.1.105, OpenBLAS 0.3.12, MKL 2020.4.304, ScaLAPACK 2.1.0

**Comment by kabicm** [comment]
Hi @antoscha,

Thanks for reporting this. The test was outdated. It is fixed in commit 3a6b12cf42efc3369e7e9d9d04d9febe3b85b571.

Cheers!

**Comment by kabicm** [comment]
Can you please confirm that it is also fixed for you?

**Comment by antoscha** [comment]
Yes, it works. Thank you!
