### ISSUE TITLE
cosma_miniapp fails if -s option is not specified.

### ISSUE THREAD

**Issue by rasolca** [eth-cscs/COSMA#70]
Even if the `-s` option is marked as optional in the doc, `cosma_miniapp` terminates with a `domain_error` exception if this option is not given a value.

Please add a default value or check if the value of the option is available before accessing it.

**Comment by kabicm** [comment]
Thanks @rasolca. This is fixed in commit 62740821cce1dbf70e4b840dbbde8187ab13f099.
