### ISSUE TITLE
feature request: add version numbers to release tarballs

### ISSUE THREAD

**Issue by dev-zero** [eth-cscs/COSMA#80]
... and also have a version number in the directory name inside the tarball

**Comment by kabicm** [comment]
You mean something like: `cosma-2.4.0.tar.gz`? We can definitely make this convention for the future releases.

**Comment by dev-zero** [comment]
Yes, and the directory inside could then also be named `cosma-2.4.0` and not just `cosma`. Thanks!

**Comment by kabicm** [comment]
This will be enforced in future releases. In fact, we are considering removing the submodules and hence the default github tarballs would include the version numbers. Anyway, should be resolved.

**Comment by dev-zero** [comment]
btw, the submodule/release-tarball thing can be [fully automated with Github Actions](https://github.com/cp2k/dbcsr/blob/develop/.github/workflows/release.yml), [git archive-all](https://pypi.org/project/git-archive-all/) and a [custom cmake target](https://github.com/cp2k/dbcsr/blob/develop/cmake/CustomTargets.cmake).

**Comment by kabicm** [comment]
Thanks @dev-zero , we will also consider that option.

**Comment by kabicm** [comment]
@dev-zero Would you maybe like to volunteer to add this? We can grant you developer rights :)
